version: '3.9'

services:
  app: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - db
  db: 
    image: postgres:15
    container_name: postgre_container
    restart: always
    environment:
      POSTGRES_USER: root       
      POSTGRES_PASSWORD: 123123 
      POSTGRES_DB: test         
    ports:
      - "5432:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data

volumes:
  postgre_data: